# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HQlSN4v-bDm5_SA14eeykiGbRi4-nMM6
"""

import streamlit as st
import pandas as pd
import numpy as np



st.title('Uber pickups in NYC')